version: '3.8'
services:
  nginx:
    image: nginx:1.21.5
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.docker/nginx/certbot/site:/etc/nginx/conf.d:ro
      - ./.docker/nginx/certbot/certs:/etc/nginx/certs:ro
      - ./.docker/nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/logs:/var/log/nginx
      - ./.docker/nginx/certbot/certbot/conf:/etc/letsencrypt
      - ./.docker/nginx/certbot/certbot/www:/var/www/certbot
    networks:
      - app_net
  certbot:
    image: certbot/certbot
    volumes:
      - ./.docker/nginx/certbot/certbot/conf:/etc/letsencrypt
      - ./.docker/nginx/certbot/certbot/www:/var/www/certbot
networks:
  app_net:
    driver: bridge
